from django.urls import path,re_path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='index'),
    path('feedback/', views.feedback, name='feedback'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contactus/', views.contactus, name='contactus'),
    path('termsofservices/', views.termsofservices, name='termsofservices'),
    path('privacypolicy/', views.privacypolicy, name='privacypolicy'),
    path('admin/', views.admin, name='admin'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('cart/', views.cart, name='cart'),
    path('borrow/', views.borrow, name='borrow'),
    path('borrowedbooks/', views.borrowedbooks, name='borrowedbooks'),
    path('forgotPassword/', 
        auth_views.PasswordResetView.as_view(template_name="forgotPassword.html"), 
        name='reset_password'),
    path('logout/', views.user_logout, name='logout'),
    path('books/', views.books, name='books'),
    path('book/<str:pk>/', views.book, name='book'),
    path('update_book/<str:pk>/',views.update_book, name='update_book'),
    # path('add_book/', views.add_book, name='add_book'),
    path('search/', views.books, name='search_books'),
    re_path(r'thumbnail/(?P<image_name>[\w\s.&]+)', views.serve_thumbnail, name='serve_thumbnail'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('clear-cart/', views.clear_cart, name='clear_cart'),
    path('all-books/', views.all_books, name='all_books'),
    path('borrow-book/', views.borrow_book, name='borrow_book'),
    path('return-book/', views.return_book, name='return_book'),
    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="resetpassword_sent.html"),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>', 
        auth_views.PasswordResetConfirmView.as_view(template_name="resetpassword_form.html"),
        name="password_reset_confirm"),
    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="resetpassword_done.html"),
        name='password_reset_complete'),
] 