# Generated by Django 5.0.4 on 2024-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='Unknown', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
