# Generated by Django 5.0.4 on 2024-05-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(default='Unknown', max_length=200),
        ),
    ]
