# Generated by Django 5.0.4 on 2024-05-06 18:03

from django.db import migrations
from members.models import Book

def seed_data(apps, schema_editor):
    Book.objects.create(id=3 , title="The Last Panda", author="George B. Schaller", isbn = 9780226736297, description="In this magnificent, heart-wrenching book--hailed Best Book of 1993 by the New York Times Book Review and USA Today--acclaimed naturalist and National Book Award winner George B. Schaller documents the plight of the mysterious panda--and urgently calls for the compassion needed to save these gentle animals from extinction. Includes a new Preface for this edition. 27-color plates.", publisher='University of Chicago Press', image="http://books.google.com/books/content?id=Ar4lEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api")
    Book.objects.create(id=4 ,title="Tracks of a Panda", author = "Nick Dowson", isbn = 9781406318715, description=	"Panda Bears.", publisher="Walker", image="http://books.google.com/books/content?id=BNBGPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api")
    



class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_book_image'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
