# Generated by Django 5.0.4 on 2024-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='Unknown', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
