# Generated by Django 5.0.4 on 2024-05-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
