# Generated by Django 5.0.4 on 2024-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
