# Generated by Django 5.0.4 on 2024-05-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_book_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesForBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/bookimages/')),
            ],
        ),
    ]
