# Generated by Django 5.0.4 on 2024-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_imagesforbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesforbooks',
            name='image',
            field=models.ImageField(upload_to='bookimages/'),
        ),
    ]
