# Generated by Django 5.0.4 on 2024-05-14 12:34

from django.db import migrations
from members.models import Book



def seed_data(apps, schema_editor):
    Book.objects.create(
        id=11,
        title="Dancing with Python",
        author="Robert S. Sutor",
        isbn="9781801071628",
        description="Develop skills in Python and Quantum Computing by implementing exciting algorithms, mathematical functions, classical searching, data analysis, plotting data, machine learning techniques, and quantum circuits. Key FeaturesCreate quantum circuits and algorithms using Qiskit and run them on quantum computing hardware and simulatorsLearn the Pythonic way to write elegant and efficient codeDelve into Python's advanced features, including machine learning, analyzing data, and searchingBook Description Dancing with Python helps you learn Python and quantum computing in a practical way. It will help you explore how to work with numbers, strings, collections, iterators, and files. The book goes beyond functions and classes and teaches you to use Python and Qiskit to create gates and circuits for classical and quantum computing. Learn how quantum extends traditional techniques using the Grover Search Algorithm and the code that implements it. Dive into some advanced and widely used applications of Python and revisit strings with more sophisticated tools, such as regular expressions and basic natural language processing (NLP). The final chapters introduce you to data analysis, visualizations, and supervised and unsupervised machine learning. By the end of the book, you will be proficient in programming the latest and most powerful quantum computers, the Pythonic way. What you will learnExplore different quantum gates and build quantum circuits with Qiskit and PythonWrite succinct code the Pythonic way using magic methods, iterators, and generatorsAnalyze data, build basic machine learning models, and plot the resultsSearch for information using the quantum Grover Search AlgorithmOptimize and test your code to run efficientlyWho this book is for The book will help you get started with coding for Python and Quantum Computing. Basic familiarity with algebra, geometry, trigonometry, and logarithms is required as the book does not cover the detailed mathematics and theory of quantum computing. You can check out the author's Dancing with Qubits book, also published by Packt, for an approachable and comprehensive introduction to quantum computing.",
        publisher="Packt Publishing Ltd",
        image="http://books.google.com/books/content?id=FQlBEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )

# Book 2
    Book.objects.create(
        id=12,
        title="Python: The No-Nonsense Guide: Learn Python Programming Within 12 Hours!",
        author="Cyberpunk University",
        isbn="9781542589406",
        description="Learn How To Program With Python In Only 12 Hours! What if you could automate your life to make it much easier? How about, building your own API's, messaging bots or create an automated coffee machine to make you coffee at the right time with the perfect temperature. Sounds good? This is just a fraction of what you could do with Python and we would love to show you how in just 12 Hours! Bullsh*t you say? Here at Cyberpunk University, we believe that we have the ability to learn Python to anybody within 12 hours. We know how quite tricky it is to learn and be a master of any programming language. Our team is comprised of professionals who have been in the industry of information technology for decades and our experience made us able to create information products such as this step-by-step guide. We took out all the bullsh*t and tell you what to do, and more important, HOW TO DO IT! What will you find in this book: - How to setup the programming language of the future - How to run Hello World the RIGHTWAY - How to use all the different data types in Python - Exercises at the end of each chapter to help you master Python - How to handle errors and exceptions when writing a program - How you can test your programs - BONUS: Compilation of valuable links and tutorials to further develop your python skills - BONUS: The FREE Cyberpunk Python Whizz Kit including, a Python Cheat sheet and 50+ Free Python exercises you can use however you want.",
        publisher="Createspace Independent Publishing Platform",
        image="http://books.google.com/books/content?id=6yPonAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api"
    )

    # Book 3
    Book.objects.create(
        id=13,
        title="Programming in Python 3: A Complete Introduction to the Python Language",
        author="Mark Summerfield",
        isbn="9780321680563",
        description="Now fully updated, this edition brings together all the knowledge...",
        publisher="Addison-Wesley Professional",
        image="http://books.google.com/books/content?id=H9emM_LGFDEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )

    # Book 4
    Book.objects.create(
        id=14,
        title="Taming PYTHON By Programming",
        author="Jeeva Jose",
        isbn="9789386173348",
        description="This is a great book for Python Beginner and Advanced Learner...",
        publisher="KHANNA PUBLISHING HOUSE",
        image="http://books.google.com/books/content?id=6HgFEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )

    # Book 5
    Book.objects.create(
        id=15,
        title="Core Python Programming",
        author="Wesley Chun",
        isbn="9780130260369",
        description="Experts and novices alike will be able to find information about every command...",
        publisher="Prentice Hall Professional",
        image="http://books.google.com/books/content?id=mh0bU6NXrBgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )

    Book.objects.create(
        id=16,
        title="Why Wars Happen",
        author="Jeremy Black",
        description="In this deeply informed book, renowned historian Jeremy Black addresses the crucial question of why wars happen, bridging the disciplines of history, political science, and international relations, and spanning over the centuries. Black marshals an astonishing range of material from all corners of the globe, and demonstrates the universalities of conflict.",
        publisher="Unknown",
        isbn="39015040336805",
        image="http://books.google.com/books/content?id=QchmAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api"
    )

    Book.objects.create(
        id=17,
        title="New & Old Wars",
        author="Mary Kaldor",
        description="Deals with the implications of 'the new wars' in the post 9-11 world. This work shows how old war thinking in Iraq has greatly exacerbated what is the archetypal new war - with insurgency, chaos and the occupying forces' lack of direction prescient of a different kind of conflict emerging in the 21st Century.",
        publisher="Polity",
        isbn="9780745638645",
        image="http://books.google.com/books/content?id=7hFnQezB6_sC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )

    Book.objects.create(
        id=18,
        title="The German Wars: A Concise History, 1859–1945",
        author="Michael A. Palmer",
        description="“A fine survey of how a nation came to be recognized for its military supremacy—despite losing two world wars.” —Midwest Book Review In the decades leading up to World War II, the world was in awe of the Prussian-German military, seeking to emulate what esteemed German military history scholar Robert M. Citino has termed “the German Way of War.” Military professionals around the globe became fluent in the tactical jargon: bewegungskrieg, schwerpunckt, auftragstaktik, fingerspitzengefuhl, and of course, blitzkrieg. At the same time, German warfare would become closely associated with the bloodiest and cruelest era in the history of mankind. The German Wars: A Concise History, 1859–1945 outlines the history of European warfare from the Wars of German Unification to the end of World War II. Author Michael A. Palmer looks at political, social, economic, and military developments across Europe and the United States during this crucial period in world history in order to demonstrate the lasting impact of the German Wars on the modern age. “Palmer has succeeded in creating an outstanding short history of the German wars that influenced the development of Europe and the world in the 19th and 20th centuries. It’s a terrific introduction and overview of the subject.” —Armchair General “A provocative look at the methods that Germany used to wage war, and why ultimately they failed.” —Military Heritage “This is an excellent book . . . highly readable. It would be an excellent addition to the library of any military historian, public library, university library as well as personal collection of persons with interest in European or Trans-Atlantic History.” —Kepler’s Military History Book Reviews",
        publisher="Quarto Publishing Group USA",
        isbn="9781616739850",
        image="http://books.google.com/books/content?id=4eHKE9NIwbMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )

    Book.objects.create(
        id=19,
        title="The SAGE International Encyclopedia of Travel and Tourism",
        author="Linda L. Lowry",
        description="Taking a global and multidisciplinary approach, The SAGE International Encyclopedia of Travel and Tourism brings together a team of international scholars to examine the travel and tourism industry, which is expected to grow at an annual rate of four percent for the next decade. In more than 500 entries spanning four comprehensive volumes, the Encyclopedia examines the business of tourism around the world paying particular attention to the social, economic, environmental, and policy issues at play. The book examines global, regional, national, and local issues including transportation, infrastructure, the environment, and business promotion. By looking at travel trends and countries large and small, the Encyclopedia analyses a wide variety of challenges and opportunities facing the industry. In taking a comprehensive and global approach, the Encyclopedia approaches the field of travel and tourism through the numerous disciplines it reaches, including the traditional tourism administration curriculum within schools of business and management, economics, public policy, as well as social science disciplines such as the anthropology and sociology. Key features include: More than 500 entries authored and signed by key academics in the field Entries on individual countries that details the health of the tourism industry, policy and planning approaches, promotion efforts, and primary tourism draws. Additional entries look at major cities and popular destinations Coverage of travel trends such as culinary tourism, wine tourism, agritourism, ecotourism, geotourism, slow tourism, heritage and cultural-based tourism, sustainable tourism, and recreation-based tourism Cross-references and further readings A Reader’s Guide grouping articles by disciplinary areas and broad themes",
        publisher="SAGE Publications",
        isbn="9781483368962",
        image="http://books.google.com/books/content?id=8RwvDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )
    
    Book.objects.create(
        id=20,
        title="Travel Medicine",
        author="Robert Steffen & Hans O. Lobel & James Haworth, and David J. Bradley",
        description="Almost 50 million persons visit another continent each year. It is mainly those 15-18 million travelers from industrialized nations who visit or reside in developing countries that are at increased health risk. To develop effective health protection advice, the health risks of travel and the benefits of prophylaxis (vaccines, new and old drugs, behaviour modification, etc.) should be assessed systematically. The purpose of this book is to improve the protection of the travelers' health by more effective and more uniform recommendations. It contains many data on recent research and represents the first comprehensive account on travel medicine for professionals.",
        publisher="Springer Science & Business Media",
        isbn="9783642737725",
        image="http://books.google.com/books/content?id=lvH0CAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )




class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_feedback'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
