# Generated by Django 5.0.4 on 2024-05-14 13:02

from django.db import migrations
from members.models import Book

def seed_data(apps, schema_editor):
    
    Book.objects.create(
        id=21,
        title="Travel Tales Monthly",
        author="Michael Brein, Ph.D.",
        isbn="9974911512478",
        description="Michael Brein’s Travel Tales Monthly is a monthly bookazine release of simply incredible travel tales, told 10 at a time. Michael Brein, aka The Travel Psychologist has made it his life’s passion to interview, now more than 1,750 world adventurers and travelers he has met throughout his world travels to more than 125 countries over the last four decades. “You wouldn’t believe the incredible stories people have told me about their travels,” says Michael when he talks about the nearly 10,000 travel tales he has amassed over the years in this way. Stories run the gamut of the good, the wonderful, and the magical, as well as, indeed, the bad, the horrible, and the truly horrific! These are--simply stated--great stories! Stories are told mainly in the present tense by interviewees, but, sadly, some are revealed about travelers who unfortunately did not live to tell their tales. These have often been related by weary, bleary-eyed travelers who felt that these tales should also be told. Into the pages of Travel Tales Monthly and then into the volumes of The Travel Psychologist Travel Tales Series ebooks will go the formerly untold tales of close calls, dangers, and great escapes; the mystical, spiritual, and the paranormal; meeting people, making friends, and incredible hospitality; harassment by beggars, hustlers, and con artists of all kinds; formidable characters met and phenomenal experiences had; and much, much more—all in the form of about 200 ebooks covering all sorts of subjects, countries and themes. The intent of Travel Tales Monthly is to present collections of tales each month, introducing you to the stories as they make their way into The Travel Psychologist Travel Tales Series in the form of completed standalone ebooks in the series. The telling of travel stories by Michael Brein via his Travel Tales Monthly as well as his travel tales ebook series is travel storytelling par excellence, but with one significant difference: Michael Brein is the world’s first and perhaps only travel psychologist. Thus, he tells the travel stories with a particular, unique psychological bent—there’s a lot of travel psychology behind everyone’s sharing of their experiences. With deft and persistence, Michael hones in on and ferrets out the usually heretofore unexplored and untold truly psychological netherworld that lurks just below the surface of most people’s travel experiences, bringing them into full view. For instance, what led up to a good or wonderful travel experience? How can we experience more of same? What was behind the horrific life-threatening or pickpocketing experience that got you caught up in in that one horrendous moment? Let’s unravel bad experiences piece by piece to see how this might have been avoided in the first place. Let’s unfold wonderful travel experiences to see how these may be repeated. What are some of the philosophical and life-changing insights gained from mystical experiences in one’s travels? What’s it like to experience your roots? How does it feel to be the first white person that others have ever seen? How does it feel like to be touched by a stranger? What is real fear like? On and on, Michael Brein delves into travel experiences from the standpoint of what is interesting, what is to be learned, and what is to be gained? How can this be made to happen again? Or NOT at all? Michael Brein is sure that you will be mesmerized and captivated by the stories you read in his Travel Tales Monthly and in his Travel Psychologist Travel Tales Series. In this Issue (No. 4 Oct 2014): Michael Brein’s Travel Tales Monthly Bookazine Issue No. 4 for October 2014 contains among the best travel stories from Michael’s huge collection of about 10,000 travel tales that he has gathered in interviews with nearly 1,750 world travelers and adventurers during his four decades of travel to more than 125 countries throughout the world. The 10 travel tales that are featured for October, as well as each following month, include a fascinating mix of travel stories as well as a few brief vignettes. The October issue features such tales as The Hug, Les Ugly Americains, and The Red Dodge, whereby travelers get themselves into trouble by behaving and acting in ways that make them ‘Persona Non-Grata’ overseas. It is difficult enough to be culturally sensitive back home. But what are the consequences of being insensitive in a strange foreign land? What do you do? And, if that is not enough for you, how about Run! Run!, our featured story for this month about an ’ugly’ American, who, in spite of himself, commits a series of simple cultural faux pas in Kathmandu—contrary to the good advice of a friend—a ‘beautiful’ American this time—which gets out of hand and morphs into a very scary, close call involving his worst nightmare and a possible threat to his life. You are going to consider this month what goes into being the ‘Good, Bad, and the Ugly’ of travel. And you will also see some aspects of travel that you may not ever have considered before. And, once again, you will certainly experience vicariously those odd vagaries of travel-life that can await you and can suddenly appear just around the corner at about any turn along the way. Dr. Loren Ekroth, our guest contributor for this month, revisits us with some very good travel advice and ‘picks.’",
        publisher="Michael Brein, Inc.",
        image="http://books.google.com/books/content?id=coDfBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    )
    
    Book.objects.create(
            id=22,
            title="DK Eyewitness Travel Guide Great Britain",
            author="DK Travel",
            isbn="9780241349786",
            description="The ideal travel companion, full of insider advice on what to see and do, plus detailed itineraries and comprehensive maps for exploring Great Britain. Visit Stonehenge's mysterious monoliths, take the sea air in buzzing Brighton or come face to face with the Vikings in York: everything you need to know is clearly laid out within colour-coded chapters. Discover the best of Great Britain with this indispensable travel guide. Inside DK Eyewitness Travel Guide Great Britain: - Over 60 colour maps help you navigate with ease - Simple layout makes it easy to find the information you need - Comprehensive tours and itineraries of Great Britain, designed for every interest and budget - Illustrations and floorplans show in detail Westminster Abbey, St Paul's Cathedral, Buckingham Palace and the Tower of London, as well as Brighton's Royal Pavilion, Canterbury Cathedral, Blenheim Palace, the Eden Project, Castle Howard, the Royal Mile and much more - Colour photographs of Great Britain's stunning landscape - bucolic countryside, spectacular coastline, rugged moorland and more - as well as architectural highlights, peaceful villages and vibrant cities - Detailed chapters, with area maps, cover London - West End and Westminster; South Kensington and Hyde Park; Regent's Park and Bloomsbury; the City and Southwark; and sights beyond the city - the Downs and Channel Coast; East Anglia; Thames Valley; Wessex; Devon and Cornwall; the Midlands; Lancashire and the Lakes; Yorkshire and the Humber Region; Northumbria; Wales; and Scotland - Historical and cultural context gives you a richer travel experience: learn about Great Britain's long history, society and politics; heraldry and aristocracy; rural architecture and stately homes; sporting highlights; and festivals and events - Experience the culture with features on the gardens of England; John Nash's Regency London; the castles of Wales; the Industrial Revolution; and more - Essential travel tips: our expert choices of where to stay, eat, shop and sightsee, plus transport, visa and health information DK Eyewitness Travel Guide Great Britain is a detailed, easy-to-use guide designed to help you get the most from your visit to Great Britain. DK Eyewitness: winner of the Top Guidebook Series in the Wanderlust Reader Travel Awards 2017. 'No other guide whets your appetite quite like this one' - The Independent Want to see more of Great Britain? Try our DK Eyewitness Travel Guide England's South Coast. About DK Eyewitness Travel: DK's highly visual Eyewitness guides show you what others only tell you, with easy-to-read maps, tips, and tours to inform and enrich your holiday. DK is the world's leading illustrated reference publisher, producing beautifully designed books for adults and children in over 120 countries.",
            publisher="Dorling Kindersley Ltd",
            image="http://books.google.com/books/content?id=9uBBDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )

    Book.objects.create(
            id=23,
            title="Travel, Tourism, and Identity",
            author="Gabriel R. Ricci",
            isbn="9781351301114",
            description="Travel, Tourism and Identity addresses the psychological and social adjustments that occur when people make contact with others outside their social, cultural, or linguistic groups. Whether such contact is the result of tourism, seeking exile, or relocating abroad, the volume's contributors demonstrate how one's identity, cultural assumptions, and worldview can be brought into question. In some cases, the traveller finds that bridging the social and cultural gap between himself and the new society is fairly easy. In other cases, the traveller discovers that reorienting himself requires absorbing a new cultural history and traditions. The contributors argue that making these adjustments will surely enhance the traveller's or tourist's experience; otherwise the traveller or tourist will be at risk of becoming a marginalized figure, one disconnected from the society that surrounds him. This latest volume in the Culture & Civilization series features a collection of essays on travel and tourism. The essays cover a range of topics from historical travels to modern social identities. They discuss ancient travels, contemporary travels in Europe, Africa and sustainable eco-tourism, and the politics of tourism. Essays also address experiences of Grenada's 'Spice Island' identity, and the effects of globalization and migrations on personal identity.",
            publisher="Routledge",
            image="http://books.google.com/books/content?id=Rm5QDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )

    Book.objects.create(
            id=24,
            title="A History of Money",
            author="John F. Chown",
            isbn="9780415102797",
            description="Introduces monetary history: money as coin, the development of credit and banking, and inconvertible paper money.",
            publisher="Psychology Press",
            image="http://books.google.com/books/content?id=UCOZpx2hjL8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )

    Book.objects.create(
            id=25,
            title="The Principles of Money and Banking",
            author="Charles Arthur Conant",
            isbn="39015065664701",
            description="Teaches you about how to manaage your money ,and how the banking system works.",
            publisher="Oxford",
            image="http://books.google.com/books/content?id=hEQ5AAAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )

    Book.objects.create(
            id=26,
            title="The Rich Men of Massachusetts",
            author="Abner Forbes",
            isbn="CHI:13635937",
            description="Containing a Statement of the Reputed Wealth of about Two Thousand Persons, with Brief Sketches of Nearly Fifteen Hundred Characters",
            publisher="Forbes Co.",
            image="http://books.google.com/books/content?id=Ix9EAQAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )

    Book.objects.create(
            id=27,
            title="Think Rich Get Rich Stay Rich",
            author="Karen Neillinger & Francine Blum",
            isbn="9781938819230",
            description="Think Rich! Get Rich! Stay Rich! is a witty whimsical approach to increase your investment savvy, overcome life's financial pitfalls, and help you obtain financial freedom and empowerment, stocks, bonds, commodities, options, real estate, and other investments become easy to understand using the book's approach.",
            publisher="Alphagraphics of Pearl, MS",
            image="https://m.media-amazon.com/images/I/91Q85lZJnwL._SL1500_.jpg"
        )

    Book.objects.create(
            id=28,
            title="Rich Dad Poor Dad - What the Rich Teach Their Kids About Money",
            author="Robert T. Kiyosaki",
            isbn="9780359727896",
            description="Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend, his rich dad — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
            publisher="Lulu.com",
            image="http://books.google.com/books/content?id=kRqeDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )

    Book.objects.create(
            id=29,
            title="Encyclopedia of British Football",
            author="Richard William Cox & Dave Russell, and Wray Vamplew",
            isbn="9780714652498",
            description="This reference work aims to provide sports enthusiasts, journalists, librarians, students and scholars with an authorative source of information on a comprehensive range of subjects covering the history and organization of football in Britain. Over 250 entries focus on key organisations or individuals, famous clubs, major competitions, events, venues and incidents, institutions and organisations as well as key issues such as gender, racism, commercialization, professionalism and drugs, alcohol and football.",
            publisher="Psychology Press",
            image="http://books.google.com/books/content?id=JKbb02bg6zYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )

    Book.objects.create(
            id=30,
            title="Football at the Park",
            author="Jenny Giles",
            isbn="9781869558192",
            description="Tim wants to play football with the big boys but they say that he is too little.",
            publisher="Nelson Thornes",
            image="http://books.google.com/books/content?id=W2xPA7R-4JsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        )



class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20240514_1534'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
